name: Build all modules

on:
  pull_request:
    types:
      - closed
env:
  GITHUB_ACTOR: ghs
  GITHUB_TOKEN: ${{ secrets.PRIVATE_KEY }}

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.9.5
      - name: prepare setting
          uses: whelk-io/maven-settings-xml-action@v22
          with:
            servers: >
              [
                {
                  "id": "github",
                  "username": "${GITHUB_ACTOR}",
                  "password": "${GITHUB_TOKEN}"
                }
              ]
            profiles: >
              [
                {
                  "id": "github",
                  "properties": {
                    "github.username": "${GITHUB_ACTOR}",
                    "github.password": "${GITHUB_TOKEN}"
                  }
                }
              ]
            output_file: ./custom.xml
      - name: release-prepare
        run: mvn -s $GITHUB_WORKSPACE/custom.xml --batch-mode release:prepare

      - name: release-perform
        if: ${{ success() }}
        run: mvn -s $GITHUB_WORKSPACE/custom.xml --batch-mode release:perform

      - name: Build and deploy to github packages
        if: ${{ success() }}
        run: mvn -s $GITHUB_WORKSPACE/custom.xml -B package

      - name: release-rollback
        if: ${{ failure() }}
        run: mvn -s $GITHUB_WORKSPACE/custom.xml -B release:rollback